language: node_js
node_js:
  - "7"
install:
  - npm install
script: npm run test
after_success:
  - npmbox npmBox --target boxes/npmbox.npmbox
  - npmbox deps/dep1.json --target boxes/dep1.npmbox
  - npmbox deps/dep2.json --target boxes/dep2.npmbox
  - npmbox deps/devdep1.json --target boxes/devdep1.npmbox
  - npmbox deps/devdep2.json --target boxes/devdep2.npmbox
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git status
  - git commit --message "npm packages $TRAVIS_BUILD_NUMBER"
  - git remote -v
  - git remote remove origin
  - git remote add origin https://travtok:${GH_TOKEN}@${GH_REF}
  - git push origin HEAD:master
env:
  global:
    - GH_REF: github.com/sadko202020/gettingNpmPackages.git
