language: node_js
node_js:
  - "7"
install:
  - npm install -g npmbox
script: npm run test
after_success:
  - rm ./boxes/*.npmbox
  - npmbox npmbox --target boxes/npmbox
  - npmbox deps/dep.json --target boxes/dep
  - npmbox deps/devdep.json --target boxes/devdep
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git status
  - git commit --message "npm packages $TRAVIS_BUILD_NUMBER"
  - git remote -v
  - git remote remove origin
  - git remote add origin https://travtok:${GH_TOKEN}@${GH_REF}
  - git push origin HEAD:master
env:
  global:
    - GH_REF: github.com/sadko202020/gettingNpmPackages.git
