language: node_js
node_js:
  - "12"
before_install:
  - mkdir npm-packages-offline-cache
  - yarn config set yarn-offline-mirror ./npm-packages-offline-cache
  - yarn config set yarn-offline-mirror-pruning true
  - mv ~/.yarnrc ./
install:
  - yarn
  - yarn add react@latest
  - yarn add redux@latest
  - yarn add webpack@latest
  - yarn add webpack-cli@latest
  - yarn add react-dom@latest
  - yarn add babel@latest
  - yarn add babel-loader@latest
  - yarn add babel-preset-react@latest
script: npm run test
after_success:
  - ls npm-packages-offline-cache
  - rm archive.tar.gz
  - tar czf archive.tar.gz npm-packages-offline-cache/
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git status
  - git commit --message "npm packages $TRAVIS_BUILD_NUMBER"
  - git remote -v
  - git remote remove origin
  - git remote add origin https://travtok:${GH_TOKEN}@${GH_REF}
  - git push origin HEAD:master
env:
  global:
    - GH_REF: github.com/sadko202020/gettingNpmPackages.git
