language: node_js
node_js:
  - "12"
install:
  - npm install
script: npm run test
after_success:
  - rm archive.tar.gz
  - tar czf archive.tar.gz node_modules/
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git status
  - git commit --message "npm packages $TRAVIS_BUILD_NUMBER"
  - git remote -v
  - git remote remove origin
  - git remote add origin https://travtok:${GH_TOKEN}@${GH_REF}
  - git push origin HEAD:master
env:
  global:
    - GH_REF: github.com/sadko202020/gettingNpmPackages.git
